### ISSUE TITLE
シングルコアとマルチコアとで一部の挙動が異なる

### ISSUE THREAD

**Issue by motitaiyaki** [SlashNephy/Tweetstorm#6]
シングルコアのマシンにて発現するように感じられるため、他Issueの内容のような改善を行うことによって解消する可能性がある

**Comment by SlashNephy** [comment]
https://github.com/SlashNephy/Tweetstorm/pull/9 で同時アクセス数の制約をオーバライドできるようになりましたが, シングルコア環境では依然としてコネクションが詰まってしまうようです。

**Comment by motitaiyaki** [comment]
#9 による `v2.0.0` から指定可能になった `max_connections` でシングルコアでも複数のアクセスを同時に受付可能になったことを確認できましたが、未だマルチコア環境に対して異なる挙動を行う場合があり、まだ少し検証が必要です。

**Comment by SlashNephy** [comment]
https://github.com/SlashNephy/Tweetstorm/commit/d37bb37d73fcb47bc5616f3def307a03070a5d48 で`max_connections`の値が同時接続数と一致しない問題を修正しました。
また https://github.com/SlashNephy/Tweetstorm/commit/3e519d60d69c45093c8916f0ff84dec1aec0c4c8でグローバルなCommonPoolの並列数を指定できる`common_pool_parallelism`オプションを追加しました。

**Comment by SlashNephy** [comment]
https://github.com/SlashNephy/Tweetstorm/commit/9ed3ae2fe26a627425e29acc7c553dd21fe0ff35 で修正されたはずです。
